[connections.snowflake]
account = "NOSBWCY-QEB55470"
user = "mellymel"
private_key_file = "eyJraWQiOiI4MzI2OTQwODU5Njg2OTE4IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiNDk2MzI0MzU2OjEyNzA1OTAzNDg4NSIsImlzcyI6IlNGOjEwNDkiLCJleHAiOjE4MDI4NzYxMDd9.H0twWDNK5LMLk5xNWt3vR2ugm97StpXd4nW-FBtbkNAv_BSjl_yDGqElkd8fBnsfmL0qLm2PTK-jNnoq9qk_Wg"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"